#!/bin/zsh

arg_filename="$pwd"

function list() {
  print -P  "in %B%F{green}$arg_filename%f%b"

  local list_file=($(ls $arg_filename -t))
  declare -i count=0

  for i in "${list_file[@]}"
  do
    count+=1
    print -P  "%B%F{yellow}[$count]%f%b %B$i%b"
    # echo "$count $i"
  done

  exit 1
}

function debug {
  echo "You used $@"
}

function parse {
  local flag_help flag_list flag_recents
  local arg_time=1440 arg_choose=1 arg_quant=1
  local usage=(
    "[-h|--help]"
  )

  zmodload zsh/zutil
  zparseopts -D -F -K -- \
    {h,-help}=flag_help \
    {s,-show-recents}=flag_recents \
    {l,-list}=flag_list \
    {c,-choose}:=arg_choose \
    {q,-quantity}:=arg_quant \
    {f,-filename}:=arg_filename ||
    return 1

  if [[ -n ${flag_help} ]]; then
    echo "help message"
    exit 1
  fi

  if [[ -n ${flag_list} ]]; then
    list "$arg_filename"
  fi

  echo "--show-recents: $flag_recents"
  echo "--list: $flag_list"
  echo "--filename: $arg_filename"
  echo "positional: $@"

}

parse "$@"
